# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo ldconfig

warnings_are_errors: true

r_packages:
  - devtools
  - maptools
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
  - covr

r_check_args: "--no-examples --no-tests --no-vignettes"
